### ISSUE TITLE
Refilling lantern removes mapping

### ISSUE THREAD

**Issue by magne4000** [Godofdrakes/WeaponPalettes#1]
Cool mod! Especially for mage builds.

Here is an issue I stumbled upon:
If I mapped some skills when having the lantern equipped, when I refill it with oil, mappings related to the lantern are gone.

**Comment by akiroth** [comment]
I really like the offhand swapping but for the same issue.  Quick test it acts like the matchUID is true for all torches and lanterns.  Of course any refilled lantern is a 'new' lantern and not the old one with restored durability.

**Comment by Godofdrakes** [comment]
This should be resolved as of v1.1.0. The mod now uses the name of an item instead of it's UID.
