### ISSUE TITLE
Saving quickslots does not work with the new version of SideLoader 3.8.3

### ISSUE THREAD

**Issue by sevboa** [Godofdrakes/WeaponPalettes#2]
Perhaps the problem is something else. But the mod is great! I really want to play with it, but it's impossible to set up quickslots again every time. Most likely, either the quickslots settings are not saved correctly, or they are not loaded correctly when the game starts.
When you exit to the main menu and select a character, the settings remain. Thanks in advance for your response!

**LogOutput.log**
[Message:   BepInEx] BepInEx 5.4.19.0 - Outward Definitive Edition (18.05.2022 20:38:32)
[Info   :   BepInEx] Running under Unity v2020.3.26.7510196
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [SideLoader 3.8.3]
[Message:SideLoader] Version 3.8.3 starting...
[Info   :   BepInEx] Loading [WeaponPalettes 1.0.0]
[Info   :WeaponPalettes] WeaponPalettes loaded
[Message:   BepInEx] Chainloader startup complete
[Message:SideLoader] Set up custom keybinding 'SideLoader Menu', actionID: 138
[Message:SideLoader] Registered SideLoader RPCManager with view ID 899
[Message:SideLoader] Cached 329 original animations.
[Message:SideLoader] Built FX prefab dictionaries
[Message:SideLoader] SideLoader Setup Finished
[Message:SideLoader] -------------------------
[Message:SideLoader] SL Setup took 0.482 seconds
[Message:SideLoader] Finished invoking OnPacksLoaded.
[Message:SideLoader] Loaded UI bundle
[Info   :WeaponPalettes] [Change] Character: JimBeam, MainHand: , OffHand: 
[Info   :WeaponPalettes] [Change] Character: JimBeam, MainHand: , OffHand: 
[Info   :WeaponPalettes] [Change] Character: JimBeam, MainHand: Bow, OffHand: 
[Message:SideLoader] Set SceneResetWanted: False
[Info   :WeaponPalettes] [Set] Character: JimBeam, Item: Топор из сырой древесины, Index:0
[Info   :WeaponPalettes] [Change] Character: JimBeam, MainHand: Bow, OffHand: 
[Message:SideLoader] Checking SL_Character spawns (Berg)
[Info   :WeaponPalettes] [Change] Character: JimBeam, MainHand: Axe_1H, OffHand: 

**WeaponPalettes.WeaponPaletteSaveExtension.xml**
`<?xml version="1.0"?>
<WeaponPaletteSaveExtension xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Data>
    <Datum>
      <WeaponSet />
      <ItemUid>L1mH6XkNdkCkyfIgGpdKXg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>1</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>1</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>1</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>hFCySnU3MEq25_I9lpvigQ</ItemUid>
      <Index>1</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>L1mH6XkNdkCkyfIgGpdKXg</ItemUid>
      <Index>0</Index>
    </Datum>
    <Datum>
      <WeaponSet />
      <ItemUid>o-2c4PfF6EGUjdYKeO27Rg</ItemUid>
      <Index>0</Index>
    </Datum>
  </Data>
</WeaponPaletteSaveExtension>`

**Comment by Godofdrakes** [comment]
This should be fixed as of v1.1.0. I was able to enter and exit the game multiple times and not lose my quickslots.
