### ISSUE TITLE
Items Lost on Weapon Switch

### ISSUE THREAD

**Issue by Fortified-Ookami** [Godofdrakes/WeaponPalettes#3]
Hi! Not sure if you are still supporting this, but I wanted to report a bug that I am encountering --

When you have an item, such as a tripwire trap, bound to a quickslot, if you use the last one in your inventory, switch weapons, and switch back, it will be gone from the quickbar.

This does not happen if you simply drop them all; it only happens when physically using the last one.

Thanks in advance if you're able to get around it at any time! :)

[output_log.txt](https://github.com/Godofdrakes/WeaponPalettes/files/9562447/output_log.txt)

**Comment by Godofdrakes** [comment]
This should be resolved as of v1.2.0
